# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build LATEST Snapshot JAR

on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        # cache: maven
    - name: Build with Maven
      run: mvn -B clean compile assembly:single 
    #- name: Generate javadocs
    #  run: mvn javadoc:javadoc
        # base-url-path: https://www.example.com/
        # user-defined-block: |
          # <meta name="referrer" content="strict-origin-when-cross-origin">
          # <link rel="icon" href="/images/favicon.svg" sizes="any" type="image/svg+xml">      
    